<?php
/* @var $block Magento\Framework\View\Element\Template */
?>
<div id="free-shipping-banner">
    <div id="free-shipping-banner" data-bind="scope:'free-shipping-banner'">
        <div data-bind="text:message"></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#free-shipping-banner": {
            "Magento_Ui/js/core/app": {
                "components":{
                    "free-shipping-banner":{
                        "component":"Luisdev_FreeShippingPromo\/js\/free-shipping-banner"
                    }
                }
            }
        }
    }
</script>
