<?php
/* @var $block Magento\Framework\View\Element\Template */
?>
<div id="free-shipping-banner">
    <div id="free-shipping-banner" data-bind="scope:'free-shipping-banner'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#free-shipping-banner": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>
